### PR TITLE
Adding DVB-CSS

### PR DESCRIPTION
**Pull request by matt-hammond-001**
Adds DVB CSS schemas using the structure discussed and agreed previously.

Have also added some initial content and links to metadata.xhtml. I'd welcome feedback on whether the way in which this has been structured is okay or if it needs changing.

This is a re-submission of #1 but based on a branch, for maintainability of my fork.

### CODE REVIEW

**Comment by c-alpha** [comment]
Thanks for your swift action, Matt!

Could I ask you to factor out the html file, please? I think wit would be more convenient to work on it if everybody does their version in a branch (i.e. can cherry pick etc.) instead of a pull request which is either accepted as a whole or not.

**Review by c-alpha — CHANGES_REQUESTED** [review]
Please remove the metadata.xhtml from the pull request, and instead put your version of it in a new branch (e.g. webpage-css). I'll then accept the pull request with the json files only. Thanks!

**Comment by matt-hammond-001** [comment]
Hi, thanks for the quick review.

If I understand correctly, the aim is to have control over how changes to `metadata.xhtml` are merged. I'm not sure I understand how putting this in a separate branch helps. I will still need to eventually submit a pull request for that branch of my fork.

Happy to make the changes you propose, but would like to ensure I understand.

**Comment by c-alpha** [comment]
A pull request can only be merged as a whole.

If you create a new branch on this repo (you have the permissions) instead of your fork, and make your changes to `metadata.xhtml` there, I/we can cherry pick upon merging; i.e. I want to merge this hunk (= paragraph), but not that one. This will give us more fine grained control within the VCS.

Of course this can all also be achieved manually outside the VCS. But then it's all just edits, and one will have to figure out from the diffs that e.g. some paragraph was merged with a pull request, but was re-removed with the next commit.

**Comment by matt-hammond-001** [comment]
Thanks for the explanation. I believe a PR is just github's UI wrapper around a merge operation (see "command line instructions" link above).

However I'm happy to go with the workflow you proposed. Will refactor shortly to separate the `metadata.xhtml` edits into a separate branch in c-alpha/metadata-website

**Comment by matt-hammond-001** [comment]
Done.

* Proposed addition of JSON and XML files remain in this PR.
* Proposed `metadata.xhtml` changes have been migrated to `c-alpha/metadata-website` repository, branch `dvb-css-website`

**Review by c-alpha — APPROVED** [review]

**Pull request merged**
